// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbbvztosjfxudhvjecle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiYnZ6dG9zamZ4dWRodmplY2xlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0OTQzMTMsImV4cCI6MjA1MzA3MDMxM30.PcXTVae0y300ksVju1QDpzSmrf5AHgYin_iuN0AmU2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
